### ISSUE TITLE
Cannot find git-process-output.zsh

### ISSUE THREAD

**Issue by kepbod** [zdharma-continuum/zinit-annex-submods#3]
When I cloned a repo as external, it said it cannot find git-process-output.zsh.
the code I used:
```
zinit ice svn silent submods"zsh-users/zsh-history-substring-search -> external"
zinit snippet PZT::modules/history-substring-search
```

**Comment by pschmitt** [comment]
That's an issue, yes.

We moved said file in zinit's core and haven't updated the path to it here.

Refs:
- https://github.com/zdharma-continuum/zinit/commit/c0f14512a0d041989f64260eaed054f7a3370d50
- https://github.com/zdharma-continuum/zinit-annex-submods/blob/master/za-submods-atclone-handler#L25
